// Generated by CoffeeScript 1.3.3
var app, assets, express, mongoose, port, posts, stylus;

posts = require('./controllers/posts');

express = require('express');

stylus = require('stylus');

assets = require('connect-assets');

mongoose = require('mongoose');

mongoose.connect('mongodb://localhost/example');

app = express();

app.use(assets());

app.use(express["static"](process.cwd() + '/public'));

app.set('view engine', 'jade');

app.get("/", posts.index);

app.get("/posts/new", posts["new"]);

app.post("/posts/create", posts.create);

port = process.env.PORT || process.env.VMC_APP_PORT || 3000;

app.listen(port, function() {
  return console.log("Listening on " + port + "\nPress CTRL-C to stop server.");
});
