// Generated by CoffeeScript 1.3.3
var Post;

Post = require('../models/Post');

module.exports = {
  index: function(req, res) {
    return Post.find({}, function(err, posts) {
      return res.render("posts/index", {
        title: "home",
        posts: posts
      });
    });
  },
  "new": function(req, res) {
    return res.render('posts/new', {
      title: "Write New Post"
    });
  },
  create: function(req, res) {
    console.log(req.body);
    return console.log('--------------------');
  },
  show: function(req, res) {
    return Post.findById(req.params.id, function(err, post) {
      return res.render('post', {
        post: post,
        title: post.title
      });
    });
  }
};
